def lazy_range(bound):
    my_integer = 0
    while my_integer < bound:
        yield my_integer
        my_integer += 1


print('lazy_range(4) = %s' % lazy_range(4))
print('range generated by lazy_range(4):')
for my_integer in lazy_range(4):
    print('next integer = %s' % my_integer)
